// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/home/avatar.vue')['default']
    ConsolePage1: typeof import('./src/components/home/ConsolePage1.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElText: typeof import('element-plus/es')['ElText']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    HomeAchievement: typeof import('./src/components/home/HomeAchievement.vue')['default']
    'HomeAchievement copy': typeof import('./src/components/home/HomeAchievement copy.vue')['default']
    HomeAvatar: typeof import('./src/components/home/HomeAvatar.vue')['default']
    HomeExperience: typeof import('./src/components/home/HomeExperience.vue')['default']
    'HomeExperience copy': typeof import('./src/components/home/HomeExperience copy.vue')['default']
    HomeSelectedWork: typeof import('./src/components/home/HomeSelectedWork.vue')['default']
    'HomeSelectedWork copy': typeof import('./src/components/home/HomeSelectedWork copy.vue')['default']
    LayoutFooter: typeof import('./src/components/layout/LayoutFooter.vue')['default']
    LayoutHeader: typeof import('./src/components/layout/LayoutHeader.vue')['default']
    LayoutMenu: typeof import('./src/components/layout/LayoutMenu.vue')['default']
    LayoutMenuMobile: typeof import('./src/components/layout/LayoutMenuMobile.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectedWorkEntrance: typeof import('./src/components/home/SelectedWorkEntrance.vue')['default']
    SvgIcon: typeof import('./src/components/icon/SvgIcon.vue')['default']
    TaskComponent: typeof import('./src/components/task/TaskComponent.vue')['default']
    TaskDataChart: typeof import('./src/components/task/TaskDataChart.vue')['default']
    WorkTitle: typeof import('./src/components/work/WorkTitle.vue')['default']
  }
}

export {}
